name = "email-worker"
main = "src/index.js"
compatibility_date = "2024-12-30"

[vars]
UPSTASH_REDIS_REST_URL = "https://modern-baboon-27609.upstash.io"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
